### ISSUE TITLE
user deletion and doc assignment

### ISSUE THREAD

**Issue by zangsir** [zangsir/coptic-xml-tool#9]
If a user is deleted by admin, what happens to the documents that are assigned to that user? 

A related question is which user a new document is assigned to by default. Currently the system assigns new docs to 'default_user', but a desirable behavior may be to assign to the creator of this document. However, at this stage the system (document editor) doesn't keep track of who is currently creating the doc (although it can do that easily). 

But if we implemented that, then after we delete a user, what will happen to the documents s/he is assigned to?

**Comment by amir-zeldes** [comment]
I'm not sure if it's actually a problem that the assignee doesn't exist:
- The assignee in the interface is just a string
- Suppose the user clicks update and that non-existent assignee is still selected - nothing changes
- Suppose the user selects a new assignee and clicks update - the assignee is changed, and on reload after the submit, the old non-existent assignee is no longer an option (since alternatives are fetched from user accounts)

So is there actually a problem with the fact that there is an assignee string which is no longer an existing user? It will by definition disappear on the next update, and since it's not a foreign key, I don't think we should see any errors. Am I missing something?

**Comment by zangsir** [comment]
No, actually you are right, there is no issue here. I think we were talking about this when there was a user table but since now user is just a string, we don't need this.
